/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type JsonValueKind = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;

export const JsonValueKind = {
    NUMBER_0: 0 as JsonValueKind,
    NUMBER_1: 1 as JsonValueKind,
    NUMBER_2: 2 as JsonValueKind,
    NUMBER_3: 3 as JsonValueKind,
    NUMBER_4: 4 as JsonValueKind,
    NUMBER_5: 5 as JsonValueKind,
    NUMBER_6: 6 as JsonValueKind,
    NUMBER_7: 7 as JsonValueKind
};