/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuditableEntityAC } from './auditableEntityAC';
import { BaseModelAC } from './baseModelAC';
import { MainDiscussionPointAC } from './mainDiscussionPointAC';
import { MomUserMappingAC } from './momUserMappingAC';
import { SubPointOfDiscussionAC } from './subPointOfDiscussionAC';
import { UserAC } from './userAC';
import { WorkProgramAC } from './workProgramAC';

export interface MomAC extends BaseModelAC { 
    workProgramId: string;
    workProgramAc?: WorkProgramAC;
    momDate: Date;
    momStartTime: Date;
    momEndTime: Date;
    closureMeetingDate: Date;
    workProgramString?: string;
    agenda?: string;
    entityId: string;
    auditableEntityAc?: AuditableEntityAC;
    mainDiscussionPointACCollection?: Array<MainDiscussionPointAC>;
    subPointDiscussionACCollection?: Array<SubPointOfDiscussionAC>;
    personResposibleACCollection?: Array<MomUserMappingAC>;
    allPersonResposibleACDataCollection?: Array<UserAC>;
    teamCollection?: Array<UserAC>;
    clientParticipantCollection?: Array<UserAC>;
    workProgramCollection?: Array<WorkProgramAC>;
    internalUserList?: Array<MomUserMappingAC>;
    externalUserList?: Array<MomUserMappingAC>;
    srNo: number;
    pdfFileString?: string;
    momDateToString?: string;
    startTime?: string;
    endTime?: string;
    closureMeetingDateToString?: string;
}