/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseModelAC } from './baseModelAC';
import { SubPointOfDiscussionAC } from './subPointOfDiscussionAC';
import { UserAC } from './userAC';

export interface MomUserMappingAC extends BaseModelAC { 
    userId: string;
    workProgram?: string;
    agenda?: string;
    name?: string;
    designation?: string;
    type?: string;
    momId?: string;
    subPointOfDiscussionId?: string;
    user?: UserAC;
    subPointDiscussionAC?: SubPointOfDiscussionAC;
}