/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ReportDisposition = 0 | 1;

export const ReportDisposition = {
    NUMBER_0: 0 as ReportDisposition,
    NUMBER_1: 1 as ReportDisposition
};