/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuditableEntity } from './auditableEntity';
import { BaseModel } from './baseModel';
import { StrategicAnalysisStatus } from './strategicAnalysisStatus';
import { User } from './user';

export interface StrategicAnalysis extends BaseModel { 
    surveyTitle?: string;
    auditableEntityName?: string;
    message?: string;
    version: number;
    status: StrategicAnalysisStatus;
    isSampling: boolean;
    auditableEntityId: string;
    detailsOfOpportunity?: string;
    estimatedValueOfOpportunity?: string;
    auditableEntity?: AuditableEntity;
}