export * from './aCMReports.service';
import { ACMReportsService } from './aCMReports.service';
export * from './account.service';
import { AccountService } from './account.service';
export * from './acm.service';
import { AcmService } from './acm.service';
export * from './auditCategories.service';
import { AuditCategoriesService } from './auditCategories.service';
export * from './auditPlans.service';
import { AuditPlansService } from './auditPlans.service';
export * from './auditProcesses.service';
import { AuditProcessesService } from './auditProcesses.service';
export * from './auditSubProcesses.service';
import { AuditSubProcessesService } from './auditSubProcesses.service';
export * from './auditTeams.service';
import { AuditTeamsService } from './auditTeams.service';
export * from './auditTypes.service';
import { AuditTypesService } from './auditTypes.service';
export * from './auditableEntities.service';
import { AuditableEntitiesService } from './auditableEntities.service';
export * from './clientParticipants.service';
import { ClientParticipantsService } from './clientParticipants.service';
export * from './countries.service';
import { CountriesService } from './countries.service';
export * from './distributors.service';
import { DistributorsService } from './distributors.service';
export * from './divisions.service';
import { DivisionsService } from './divisions.service';
export * from './entityCategories.service';
import { EntityCategoriesService } from './entityCategories.service';
export * from './entityDocuments.service';
import { EntityDocumentsService } from './entityDocuments.service';
export * from './entityRelationMappings.service';
import { EntityRelationMappingsService } from './entityRelationMappings.service';
export * from './entityTypes.service';
import { EntityTypesService } from './entityTypes.service';
export * from './locations.service';
import { LocationsService } from './locations.service';
export * from './moms.service';
import { MomsService } from './moms.service';
export * from './observationCategories.service';
import { ObservationCategoriesService } from './observationCategories.service';
export * from './observationsManagement.service';
import { ObservationsManagementService } from './observationsManagement.service';
export * from './primaryGeographicalAreas.service';
import { PrimaryGeographicalAreasService } from './primaryGeographicalAreas.service';
export * from './ratings.service';
import { RatingsService } from './ratings.service';
export * from './rcmProcess.service';
import { RcmProcessService } from './rcmProcess.service';
export * from './rcmSector.service';
import { RcmSectorService } from './rcmSector.service';
export * from './rcmSubProcess.service';
import { RcmSubProcessService } from './rcmSubProcess.service';
export * from './regions.service';
import { RegionsService } from './regions.service';
export * from './relationshipTypes.service';
import { RelationshipTypesService } from './relationshipTypes.service';
export * from './reportDistributors.service';
import { ReportDistributorsService } from './reportDistributors.service';
export * from './reportObservations.service';
import { ReportObservationsService } from './reportObservations.service';
export * from './reports.service';
import { ReportsService } from './reports.service';
export * from './riskAssessments.service';
import { RiskAssessmentsService } from './riskAssessments.service';
export * from './riskControlMatrixes.service';
import { RiskControlMatrixesService } from './riskControlMatrixes.service';
export * from './samplings.service';
import { SamplingsService } from './samplings.service';
export * from './states.service';
import { StatesService } from './states.service';
export * from './strategicAnalyses.service';
import { StrategicAnalysesService } from './strategicAnalyses.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './workPrograms.service';
import { WorkProgramsService } from './workPrograms.service';
export const APIS = [ACMReportsService, AccountService, AcmService, AuditCategoriesService, AuditPlansService, AuditProcessesService, AuditSubProcessesService, AuditTeamsService, AuditTypesService, AuditableEntitiesService, ClientParticipantsService, CountriesService, DistributorsService, DivisionsService, EntityCategoriesService, EntityDocumentsService, EntityRelationMappingsService, EntityTypesService, LocationsService, MomsService, ObservationCategoriesService, ObservationsManagementService, PrimaryGeographicalAreasService, RatingsService, RcmProcessService, RcmSectorService, RcmSubProcessService, RegionsService, RelationshipTypesService, ReportDistributorsService, ReportObservationsService, ReportsService, RiskAssessmentsService, RiskControlMatrixesService, SamplingsService, StatesService, StrategicAnalysesService, UsersService, WorkProgramsService];
