/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CountryAC } from '../model/countryAC';
import { PaginationOfPrimaryGeographicalAreaAC } from '../model/paginationOfPrimaryGeographicalAreaAC';
import { PrimaryGeographicalAreaAC } from '../model/primaryGeographicalAreaAC';
import { ProblemDetails } from '../model/problemDetails';
import { ProvinceStateAC } from '../model/provinceStateAC';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PrimaryGeographicalAreasService {

    protected basePath = 'http://localhost:5000/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public primaryGeographicalAreasAddPrimaryGeographicalArea(body: PrimaryGeographicalAreaAC, observe?: 'body', reportProgress?: boolean): Observable<PrimaryGeographicalAreaAC>;
    public primaryGeographicalAreasAddPrimaryGeographicalArea(body: PrimaryGeographicalAreaAC, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PrimaryGeographicalAreaAC>>;
    public primaryGeographicalAreasAddPrimaryGeographicalArea(body: PrimaryGeographicalAreaAC, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PrimaryGeographicalAreaAC>>;
    public primaryGeographicalAreasAddPrimaryGeographicalArea(body: PrimaryGeographicalAreaAC, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling primaryGeographicalAreasAddPrimaryGeographicalArea.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<PrimaryGeographicalAreaAC>('post',`${this.basePath}/api/PrimaryGeographicalAreas`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param versionId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public primaryGeographicalAreasAddPrimaryGeographicalAreaInNewVersion(body: Array<PrimaryGeographicalAreaAC>, versionId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public primaryGeographicalAreasAddPrimaryGeographicalAreaInNewVersion(body: Array<PrimaryGeographicalAreaAC>, versionId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public primaryGeographicalAreasAddPrimaryGeographicalAreaInNewVersion(body: Array<PrimaryGeographicalAreaAC>, versionId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public primaryGeographicalAreasAddPrimaryGeographicalAreaInNewVersion(body: Array<PrimaryGeographicalAreaAC>, versionId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling primaryGeographicalAreasAddPrimaryGeographicalAreaInNewVersion.');
        }

        if (versionId === null || versionId === undefined) {
            throw new Error('Required parameter versionId was null or undefined when calling primaryGeographicalAreasAddPrimaryGeographicalAreaInNewVersion.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/api/PrimaryGeographicalAreas/${encodeURIComponent(String(versionId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public primaryGeographicalAreasDeletePrimaryGeographicalArea(id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public primaryGeographicalAreasDeletePrimaryGeographicalArea(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public primaryGeographicalAreasDeletePrimaryGeographicalArea(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public primaryGeographicalAreasDeletePrimaryGeographicalArea(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling primaryGeographicalAreasDeletePrimaryGeographicalArea.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/api/PrimaryGeographicalAreas/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param regionId 
     * @param entityId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public primaryGeographicalAreasGetCountryListByRegion(regionId?: string, entityId?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<CountryAC>>;
    public primaryGeographicalAreasGetCountryListByRegion(regionId?: string, entityId?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CountryAC>>>;
    public primaryGeographicalAreasGetCountryListByRegion(regionId?: string, entityId?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CountryAC>>>;
    public primaryGeographicalAreasGetCountryListByRegion(regionId?: string, entityId?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (regionId !== undefined && regionId !== null) {
            queryParameters = queryParameters.set('regionId', <any>regionId);
        }
        if (entityId !== undefined && entityId !== null) {
            queryParameters = queryParameters.set('entityId', <any>entityId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<CountryAC>>('get',`${this.basePath}/api/PrimaryGeographicalAreas/get-countries-by-region`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param entityId 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public primaryGeographicalAreasGetPrimaryGeographicalAreaDetails(entityId: string, id?: string, observe?: 'body', reportProgress?: boolean): Observable<PrimaryGeographicalAreaAC>;
    public primaryGeographicalAreasGetPrimaryGeographicalAreaDetails(entityId: string, id?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PrimaryGeographicalAreaAC>>;
    public primaryGeographicalAreasGetPrimaryGeographicalAreaDetails(entityId: string, id?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PrimaryGeographicalAreaAC>>;
    public primaryGeographicalAreasGetPrimaryGeographicalAreaDetails(entityId: string, id?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (entityId === null || entityId === undefined) {
            throw new Error('Required parameter entityId was null or undefined when calling primaryGeographicalAreasGetPrimaryGeographicalAreaDetails.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (id !== undefined && id !== null) {
            queryParameters = queryParameters.set('id', <any>id);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<PrimaryGeographicalAreaAC>('get',`${this.basePath}/api/PrimaryGeographicalAreas/${encodeURIComponent(String(entityId))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param pageIndex 
     * @param pageSize 
     * @param searchString 
     * @param entityId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public primaryGeographicalAreasGetPrimaryGeographicalAreaList(pageIndex?: number, pageSize?: number, searchString?: string, entityId?: string, observe?: 'body', reportProgress?: boolean): Observable<PaginationOfPrimaryGeographicalAreaAC>;
    public primaryGeographicalAreasGetPrimaryGeographicalAreaList(pageIndex?: number, pageSize?: number, searchString?: string, entityId?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PaginationOfPrimaryGeographicalAreaAC>>;
    public primaryGeographicalAreasGetPrimaryGeographicalAreaList(pageIndex?: number, pageSize?: number, searchString?: string, entityId?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PaginationOfPrimaryGeographicalAreaAC>>;
    public primaryGeographicalAreasGetPrimaryGeographicalAreaList(pageIndex?: number, pageSize?: number, searchString?: string, entityId?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {





        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (pageIndex !== undefined && pageIndex !== null) {
            queryParameters = queryParameters.set('pageIndex', <any>pageIndex);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }
        if (searchString !== undefined && searchString !== null) {
            queryParameters = queryParameters.set('searchString', <any>searchString);
        }
        if (entityId !== undefined && entityId !== null) {
            queryParameters = queryParameters.set('entityId', <any>entityId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<PaginationOfPrimaryGeographicalAreaAC>('get',`${this.basePath}/api/PrimaryGeographicalAreas`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param countryId 
     * @param entityId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public primaryGeographicalAreasGetStateByCountryId(countryId?: string, entityId?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<ProvinceStateAC>>;
    public primaryGeographicalAreasGetStateByCountryId(countryId?: string, entityId?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ProvinceStateAC>>>;
    public primaryGeographicalAreasGetStateByCountryId(countryId?: string, entityId?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ProvinceStateAC>>>;
    public primaryGeographicalAreasGetStateByCountryId(countryId?: string, entityId?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (countryId !== undefined && countryId !== null) {
            queryParameters = queryParameters.set('countryId', <any>countryId);
        }
        if (entityId !== undefined && entityId !== null) {
            queryParameters = queryParameters.set('entityId', <any>entityId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<ProvinceStateAC>>('get',`${this.basePath}/api/PrimaryGeographicalAreas/get-states-by-country`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public primaryGeographicalAreasUpdatePrimaryGeographicalArea(body: PrimaryGeographicalAreaAC, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public primaryGeographicalAreasUpdatePrimaryGeographicalArea(body: PrimaryGeographicalAreaAC, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public primaryGeographicalAreasUpdatePrimaryGeographicalArea(body: PrimaryGeographicalAreaAC, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public primaryGeographicalAreasUpdatePrimaryGeographicalArea(body: PrimaryGeographicalAreaAC, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling primaryGeographicalAreasUpdatePrimaryGeographicalArea.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/api/PrimaryGeographicalAreas`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
